# custom hyprlock pam — no fail delay on wrong password
auth        optional    pam_faildelay.so  delay=0
auth        requisite   pam_nologin.so
auth        [success=2 default=ignore]  pam_unix.so  nodelay  nullok
auth        [success=1 default=ignore]  pam_sss.so  use_first_pass
auth        requisite   pam_deny.so
auth        required    pam_permit.so
auth        optional    pam_cap.so
